---
- name: Copy geonames-api source code
  synchronize: src="geonames-api/" dest="{{ docker_geonames_api_path }}"

- name: Create apidoc config
  copy: content="{{apidoc_conf | to_json}}" dest="{{ docker_geonames_api_path }}/apidoc.json" force=yes

- name: Build geonames-api image
  docker_image:
    path: "{{ docker_geonames_api_path }}"
    name: geonames-api
    force: true

- name: Start geonames-api
  docker_container:
    name: geonames-api-c
    image: geonames-api
    state: started
    restart: true
    env:
      ELASTICSEARCH_HOST: "{{ansible_default_ipv4.address}}:9200"
    ports:
      - "{{main_server_port}}:80"

- name: Wait for API
  uri: 
    url: "http://{{ansible_host}}/api/lookup?q=test"
  register: result
  until: "result.status == 200"
  retries: 6
  delay: 10
  tags: api-tests

- name: Run API tests
  uri: 
    url: "http://{{ansible_host}}/api/lookup"
    body:
      q: "{{item.name}}"
    body_format: json
  with_items: "{{test_lookups}}"
  tags: api-tests
  register: test_results

# - debug: var=test_results
#   tags: api-tests

- name: Check test results
  assert: that="test_results.results[item.0].json.hits.0._source.id == item.1.id"
  with_indexed_items: "{{test_lookups}}"
  tags: api-tests
