---
- name: Install common packages from apt
  apt: pkg={{item}} state=installed update_cache=yes
  with_items:
    - git
    - python3-pip
    - python3-dev
    - curl
    - zip
- name: Install global python modules
  pip: name={{item}}
  with_items:
    - awscli
    - virtualenv
- name: Create aws crendentials directory
  file: path=~/.aws state=directory
- name: Create aws credentials
  template: src=config.j2 dest=~/.aws/config
